import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


def print_intro():
    print("=" * 60)
    print("  OTT 플랫폼 감성 분석 - Netflix vs Disney+")
    print("  MobileBERT 기반 Google Play Store 리뷰 감성 분류")
    print("  분석 기간: 2020 ~ 2025  |  약 50만 건 리뷰")
    print("=" * 60)
    print()
    print("[분석 개요]")
    print("  - 데이터  : Google Play Store")
    print("  - 모델    : MobileBERT (google/mobilebert-uncased)")
    print("  - 목표 정확도 : 0.85 이상")
    print("  - 최종 정확도 : 약 0.925")
    print()
    print("=" * 60)
    print("  서론 01 | Netflix vs Disney+ 앱 사용 경험")
    print("=" * 60)
    print()
    print("[Netflix - 넷플릭스]")
    print("  [장점]")
    print("  - 압도적인 오리지널 콘텐츠 보유량")
    print("  - 정교한 AI 추천 알고리즘")
    print("  - 4K/HDR 고화질 스트리밍 지원")
    print("  - 다양한 장르 및 국가별 콘텐츠")
    print("  - 직관적이고 안정적인 앱 UI/UX")
    print("  [단점]")
    print("  - 지속적인 구독료 인상으로 부담 증가")
    print("  - 계정 공유 제한으로 가족 이용 불편")
    print("  - 광고 요금제 도입에 따른 불만")
    print("  - 일부 인기 콘텐츠 돌연 삭제")
    print()
    print("[Disney+ - 디즈니플러스]")
    print("  [장점]")
    print("  - 마블/스타워즈/픽사 강력한 IP")
    print("  - 디즈니 클래식 명작 전편 제공")
    print("  - 가족/키즈 친화적 콘텐츠 특화")
    print("  - 독점 신작 시리즈 지속 공개")
    print("  - 합리적인 초기 구독 요금")
    print("  [단점]")
    print("  - 잦은 앱 충돌/로딩 지연 문제")
    print("  - 로그인 오류 및 인증 실패 빈번")
    print("  - 버그 수정 업데이트 느린 대응")
    print("  - 넷플릭스 대비 콘텐츠 다양성 부족")
    print()
    print("=" * 60)
    print("  서론 02 | 사용자가 느끼는 불편함과 만족감")
    print("=" * 60)
    print()
    print("[Netflix - 불편한 점]")
    print("  - 구독료 지속 인상 -> 경제적 부담")
    print("  - 계정 공유 제한으로 가족 불편")
    print("  - 광고 요금제 도입 반발")
    print("  - 인기 콘텐츠 갑작스러운 삭제")
    print("[Netflix - 좋았던 점]")
    print("  - 방대한 오리지널 콘텐츠 보유")
    print("  - 높은 정확도의 추천 알고리즘")
    print("  - 다양한 장르/국가별 콘텐츠")
    print("  - 4K/HDR 고화질 스트리밍 지원")
    print()
    print("[Disney+ - 불편한 점]")
    print("  - 잦은 앱 충돌/버퍼링 오류")
    print("  - 로그인 실패 및 인증 오류")
    print("  - 화면 멈춤/로딩 지연 문제")
    print("  - 기술적 버그 수정 느린 대응")
    print("[Disney+ - 좋았던 점]")
    print("  - 마블/스타워즈 등 강력한 IP")
    print("  - 픽사/디즈니 클래식 명작 보유")
    print("  - 가족/키즈 친화적 콘텐츠")
    print("  - 독점 시리즈 공개 기대감")
    print()
    print("=" * 60)
    print("  본격 분석 시작")
    print("=" * 60)
    print()


if __name__ == "__main__":
    print_intro()

    print("=" * 60)
    print("  STEP 1: Google Play Store 리뷰 데이터 수집")
    print("=" * 60)
    import step1_collect_data
    step1_collect_data.main()

    print("=" * 60)
    print("  STEP 2: EDA 탐색적 데이터 분석")
    print("=" * 60)
    import step2_eda
    step2_eda.main()

    print("=" * 60)
    print("  STEP 3: 텍스트 전처리 및 라벨링")
    print("=" * 60)
    import step3_preprocess
    step3_preprocess.main()

    print("=" * 60)
    print("  STEP 4: MobileBERT 모델 학습")
    print("=" * 60)
    import step4_finetune
    step4_finetune.main()

    print("=" * 60)
    print("  STEP 5/6: 감성 추론 및 비즈니스 인사이트 분석")
    print("=" * 60)
    import step5_6_inference_analysis
    step5_6_inference_analysis.main()

    print()
    print("=" * 60)
    print("  전체 파이프라인 실행 완료!")
    print("  결과물 저장 위치:")
    print("    - data/combined_reviews_raw.csv   (수집 원본)")
    print("    - data/processed_labeled.csv      (전처리 완료)")
    print("    - data/predictions.csv            (감성 추론 결과)")
    print("    - models/mobilebert_ott/          (학습된 모델)")
    print("    - results/                        (모든 시각화 이미지)")
    print("=" * 60)